name: holly_quran
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.6.0+11

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  #font_awesome_flutter: ^10.3.0
  go_router: ^6.0.1
  #equatable: ^2.0.5
  #dartz: ^0.10.1
  dio: ^4.0.6
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  animated_bottom_navigation_bar: ^1.1.0+1
  change_app_package_name: ^1.1.0
  shared_preferences: ^2.0.17
  #internet_connection_checker: ^1.0.0+1
  lottie: ^2.2.0
  #webview_flutter: ^4.0.2
  quran: ^1.2.0
  awesome_dialog: ^3.0.2
  flutter_native_splash: ^2.2.16
  adhan: ^2.0.0-nullsafety.2
  intl: ^0.17.0
  location: ^4.4.0
  hijri: ^3.0.0
  flutter_fortune_wheel: ^1.2.0
  signature: ^5.3.0
  carousel_slider: ^4.2.1
  flutter_local_notifications: ^8.2.0
  timezone: ^0.8.0
  share_plus: ^6.3.1
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.3

# flutter_native_splash
flutter_native_splash:
  color: "#673AB7"
  image: assets/images/splash.jpg
  fill: true
  fullscreen: true
  android: true
  ios: true
  web: true

#flutter_icons
flutter_icons:
  android: true
  image_path: "assets/images/icon.jpg"
  ios: true

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/json/
    - assets/quran_data/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-Light.ttf
        - asset: assets/fonts/Cairo/Cairo-SemiBold.ttf
        - asset: assets/fonts/Cairo/Cairo-Black.ttf
        - asset: assets/fonts/Cairo/Cairo-ExtraLight.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf